---
title: "LGA Analysis of Victoria"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


THis is an example analysis where we will be using R, Markdown and Leaflet to create an interactive HTML document.

```{r load , warning=FALSE, comment=FALSE, warning=FALSE,  message=FALSE}

#Load Libraries

library(leaflet)
library(geojsonio)
library(viridis)
library(dplyr)
library(readr)

#Load GeoJson Data from DHHS Web API 
LGA <- geojsonio::geojson_read("http://data-dhs.opendata.arcgis.com/datasets/1d451fe314e34caa8f563529c242da26_0.geojson", what = "sp")

```

### Percentage share of Aboriginal population in Victoria

You can also embed Maps, for example:

```{r Map}


LGA$AboriginalPop <- LGA$AboriginalPop * 100

#create the colour scale
pal <- colorNumeric("viridis", NULL)


#Create the map
#Use % of population who are Aboriginal
leaflet(LGA) %>%
  addTiles() %>%
  addPolygons(stroke = TRUE, 
              weight = 1, 
              color = "white",
              smoothFactor = 0.8, fillOpacity = .5,
              fillColor = ~pal(AboriginalPop),
              label = ~paste0(LGA_NAME15, ": ", formatC(AboriginalPop, big.mark = ","))
              ) %>%
  addLegend(pal = pal, values = ~AboriginalPop, opacity = 1.0,
                         labFormat = labelFormat(transform = function(x) round(x)))



```

